t="_"*13
u,j,k,f,h,i,m,n,z=[t[:-a] for a in range(1,10)]
print(f"""{t}*{t}__
{u}***{t}_
{j}*o_o*{t}
{k}*o___o*{u}
{f}*o{n}o*{j}
{h}*o___o___o*{k}
{i}*o___o_o___o*{f}
{m}*o_o_o___o_o_o*{h}
{n}*___*o{n}o*___*{i}
{h}*o{i}o*{k}
{i}*o{z}o{z}o*{f}
{m}*o{z}o_o{z}o*{h}
{n}*o{z}o___o{z}o*{i}
{z}*o__o_o{n}o_o__o*{m}
{h}*o{i}o*{k}
{i}*o{f}o*{f}
{m}*o{j}o*{h}
{n}*o{t}o*{i}
{z}*o{t}__o*{m}
___*o{t}{z}o*{n}
__*o{t}{m}o*{z}
_*{"o_"*11+"o*___"}
{u}o_o{t}_
{u}o_o{t}_
{u}o_o{t}_
{u}o_o{t}_
{u}o_o{t}_
{u}ooo{t}_""")